services:
  db:
    image: postgres:16
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_ADMIN_USER
      POSTGRES_PASSWORD: $POSTGRES_ADMIN_PASSWORD
    volumes:
      - /var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
